apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ensenso

resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: someregistry/ensenso
    newName: registry.code.wabo.run/andre.kuehnert/enenso
